version: "3"

services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
  lint:
    image: "buildkite/plugin-linter"
    command: ["--id", "envato/git-checkout-flags"]
    volumes:
      - ".:/plugin:ro"
  shellcheck:
    image: koalaman/shellcheck
    command: ["--color=always", "hooks/pre-checkout"]
    working_dir: /plugin
    volumes:
      - ".:/plugin:ro"
